"""extend review table for ai response

Revision ID: 0ed5ed05ed6c
Revises: 3eba865a32d8
Create Date: 2026-07-08 14:22:29.678429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed5ed05ed6c'
down_revision: Union[str, None] = '3eba865a32d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('review', sa.Column('overall_comment', sa.Text(), nullable=True))
    op.add_column('review', sa.Column('risk', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'risk')
    op.drop_column('review', 'overall_comment')
    op.drop_column('review', 'summary')
    # ### end Alembic commands ###
