"""extend review table for github api using

Revision ID: 8626e8ecce58
Revises: 0ed5ed05ed6c
Create Date: 2026-07-10 00:10:16.739027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8626e8ecce58'
down_revision: Union[str, None] = '0ed5ed05ed6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('pr_url', sa.String(), nullable=True))
    op.alter_column('review', 'diff',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'diff',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('review', 'pr_url')
    # ### end Alembic commands ###
